import type { Combatant } from './types';

export const VILLAGERS: Combatant[] = [
  {
    name: 'Dog',
    hp: 3,
    attack_speed: 25,
    hit_chance: 0.7,
    min_damage: 1.0,
    max_damage: 2.0,
    image_name: 'Dog',
    stun_chance: 0,
  },
  {
    name: 'Explorer',
    hp: 3,
    attack_speed: 20,
    hit_chance: 0.7,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Explorer',
    stun_chance: 0,
  },
  {
    name: 'Fisher',
    hp: 5,
    attack_speed: 20,
    hit_chance: 0.6,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Fisherman',
    stun_chance: 0,
  },
  {
    name: 'Friendly Pirate',
    hp: 5,
    attack_speed: 20,
    hit_chance: 0.6,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'FriendlyPirate',
    stun_chance: 0.15,
  },
  {
    name: 'Militia',
    hp: 6,
    attack_speed: 15,
    hit_chance: 0.8,
    min_damage: 1.0,
    max_damage: 2.0,
    image_name: 'Militia',
    stun_chance: 0,
  },
  {
    name: 'Swordsman',
    hp: 7,
    attack_speed: 15,
    hit_chance: 0.9,
    min_damage: 2.0,
    max_damage: 2.0,
    image_name: 'Swordman',
    stun_chance: 0,
  },
  {
    name: 'Trained Monkey',
    hp: 2,
    attack_speed: 25,
    hit_chance: 0.6,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'TrainedMonkey',
    stun_chance: 0,
  },
  {
    name: 'Villager',
    hp: 5,
    attack_speed: 20,
    hit_chance: 0.6,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Villager',
    stun_chance: 0,
  },
];

export const ENEMIES: Combatant[] = [
  {
    name: 'Bear',
    hp: 10,
    attack_speed: 30,
    hit_chance: 0.33,
    min_damage: 2.0,
    max_damage: 4.0,
    image_name: 'Bear',
    stun_chance: 0.1,
  },
  {
    name: 'Demon',
    hp: 99,
    attack_speed: 15,
    hit_chance: 0.75,
    min_damage: 1.0,
    max_damage: 3.0,
    image_name: 'Demon',
    stun_chance: 0,
  },
  {
    name: 'Demon Lord',
    hp: 666,
    attack_speed: 15,
    hit_chance: 0.75,
    min_damage: 1.0,
    max_damage: 3.0,
    image_name: 'DemonLord',
    stun_chance: 0,
  },
  {
    name: 'Giant Rat',
    hp: 12,
    attack_speed: 30,
    hit_chance: 0.5,
    min_damage: 2.0,
    max_damage: 2.0,
    image_name: 'Big-Rat',
    stun_chance: 0,
  },
  {
    name: 'Goblin',
    hp: 5,
    attack_speed: 20,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 2.0,
    image_name: 'Goblin',
    stun_chance: 0,
  },
  {
    name: 'Kraken',
    hp: 150,
    attack_speed: 20,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Kraken',
    stun_chance: 0.1,
  },
  {
    name: 'Momma Crab',
    hp: 50,
    attack_speed: 20,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 2.0,
    image_name: 'MammaCrab',
    stun_chance: 0.2,
  },
  {
    name: 'Pirate',
    hp: 3,
    attack_speed: 20,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 2.0,
    image_name: 'AngryPirate',
    stun_chance: 0.2,
  },
  {
    name: 'Rat',
    hp: 3,
    attack_speed: 30,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Small-Rat',
    stun_chance: 0,
  },
  {
    name: 'Seagull',
    hp: 3,
    attack_speed: 20,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Seagull',
    stun_chance: 0,
  },
  {
    name: 'Skeleton',
    hp: 5,
    attack_speed: 30,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 2.0,
    image_name: 'Skeleton',
    stun_chance: 0.1,
  },
  {
    name: 'Slime',
    hp: 8,
    attack_speed: 30,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Big-Slime',
    stun_chance: 0,
  },
  {
    name: 'Small Slime',
    hp: 2,
    attack_speed: 50,
    hit_chance: 0.5,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Small-Slime',
    stun_chance: 0,
  },
  {
    name: 'Snake',
    hp: 3,
    attack_speed: 20,
    hit_chance: 0.6,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Snake',
    stun_chance: 0,
  },
  {
    name: 'Tentacle',
    hp: 50,
    attack_speed: 20,
    hit_chance: 0.4,
    min_damage: 1.0,
    max_damage: 1.0,
    image_name: 'Tentacle',
    stun_chance: 0.2,
  },
  {
    name: 'Tiger',
    hp: 5,
    attack_speed: 20,
    hit_chance: 0.5,
    min_damage: 2.0,
    max_damage: 3.0,
    image_name: 'Tiger',
    stun_chance: 0.2,
  },
  {
    name: 'Wolf',
    hp: 10,
    attack_speed: 30,
    hit_chance: 0.33,
    min_damage: 1.0,
    max_damage: 3.0,
    image_name: 'Wolf',
    stun_chance: 0,
  },
];
